apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-web-hello-world
    release: go-web-hello-world
  name: go-web-hello-world
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 31081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
   app: go-web-hello-world
   release: go-web-hello-world
  sessionAffinity: None
  type: NodePort
